language: objective-c
osx_image: xcode9.4

cache:
  directories:
  - Crypto/Pods/BitcoinKit/Libraries

before_install:
  - gem install xcpretty-travis-formatter --no-rdoc --no-ri --no-document --quiet
  - pod repo update
  - pod install --project-directory=Crypto
  - sh Crypto/Pods/BitcoinKit/setup/build_libraries.sh # BitcoinKit needs some additional scripts installed

install:
  # Install swiftlint through precompiled .pkg, as that is the fastest approach
  - wget --output-document /tmp/SwiftLint.pkg https://github.com/realm/SwiftLint/releases/download/0.26.0/SwiftLint.pkg && sudo installer -pkg /tmp/SwiftLint.pkg -target /

before_script:
  - cd Crypto

script:
  - set -o pipefail && xcodebuild clean test -workspace Crypto.xcworkspace -scheme CryptoTests CODE_SIGNING_REQUIRED=NO -destination 'platform=iOS Simulator,name=iPhone X,OS=11.4' | xcpretty -f `xcpretty-travis-formatter`

after_success:
  - bash <(curl -s https://codecov.io/bash)

git:
  depth: 1
