version: 2
jobs:
  swiftlint:
    docker:
      - image: dantoml/swiftlint:latest
    steps:
      - checkout
      - run: cd Client && swiftlint lint --reporter junit | tee result.xml
      - store_artifacts:
          path: result.xml
      - store_test_results:
          path: result.xml
  build-and-test:
    macos:
      xcode: "10.1.0"
    working_directory: ~/arkecosystem/crypto
    steps:
      - checkout
      - run:
          name: Install prerequisits
          command: |
            brew install carthage || true
            brew outdated carthage || brew upgrade carthage
      - run:
          name: Navigate to correct folder
          command: cd Client && carthage bootstrap --cache-builds  --platform Mac
      - run:
          name: Build and run tests
          command: cd Client && set -o pipefail && xcodebuild clean test -project Client.xcodeproj -scheme ClientTests CODE_SIGNING_REQUIRED=NO
      - run:
          name: Codecov
          when: on_success
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  lint-build-test:
    jobs:
      - swiftlint
      - build-and-test
